version: "3.9"

name: es-plugin

networks:
  es-plugin:

services:

  elasticsearch:
    image: elasticsearch:8.14.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx1024m
      xpack.security.enabled: "false"
      indices.id_field_data.enabled: "true"
    ports:
      - protocol: tcp
        target: 9200
        published: 9200
    volumes:
      - "${PWD}/elasticsearch/index-refresh-plugin-1.0_8.14.1.zip:/usr/share/elasticsearch/index-refresh-plugin-1.0_8.14.1.zip"
    networks:
      es-plugin:

  kibana:
    image: kibana:8.14.1
    ports:
      - protocol: tcp
        target: 5601
        published: 5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      es-plugin:
