version: "3.9"

name: es-plugin

networks:
  es-plugin:

services:

  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx1024m
      xpack.security.enabled: "false"
      indices.id_field_data.enabled: "true"
    ports:
      - protocol: tcp
        target: 9200
        published: 9200
    volumes:
      - "${PWD}/elasticsearch/engine-plugin-1.0-SNAPSHOT.zip:/usr/share/elasticsearch/engine-plugin-1.0-SNAPSHOT.zip"
    networks:
      es-plugin:

  kibana:
    image: kibana:8.14.3
    ports:
      - protocol: tcp
        target: 5601
        published: 5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      es-plugin:
